server_settings:
    http_port: :80
    debug: true
newsapi_settings:
    url: https://newsapi.org
    api_key: 13be2aecc0cc40248111c59bedebefeb
articleparser_settings:
    url: https://us-central1-nwfacts.cloudfunctions.net/ArticleParser
